#!/bin/bash

optt=$1

if [ "$optt" = "upd" ]; then
        echo "Updating"
	sudo apt update -y && sudo apt upgrade -y && sudo apt autoremove -y
elif [ "$optt" = "bkp" ]; then
        echo "Taking Backup"
	sudo tar -zcf /var/backups/home.tgz /home/
else
        echo -e "SELECT AN OPTION \n 1.Update (upd) \n 2.Backup (bkp)"
fi
